export const FOOD_PLACE_MAP = {
    //Minecraft
    "minecraft:mushroom_stew": "displaydelight:mushroom_stew",
    "minecraft:rabbit_stew": "displaydelight:rabbit_stew",
    "minecraft:beetroot_soup": "displaydelight:beetroot_soup",

    //Farmer's Delight
    "farmersdelight:fruit_salad": "displaydelight:fruit_salad",
    "farmersdelight:glow_berry_custard": "displaydelight:glow_berry_custard",
    "farmersdelight:cooked_rice": "displaydelight:cooked_rice",
    "farmersdelight:mixed_salad": "displaydelight:mixed_salad",
    "farmersdelight:nether_salad": "displaydelight:nether_salad",
    "farmersdelight:beef_stew": "displaydelight:beef_stew",
    "farmersdelight:chicken_soup": "displaydelight:chicken_soup",
    "farmersdelight:vegetable_soup": "displaydelight:vegetable_soup",
    "farmersdelight:fish_stew": "displaydelight:fish_stew",
    "farmersdelight:fried_rice": "displaydelight:fried_rice",
    "farmersdelight:pumpkin_soup": "displaydelight:pumpkin_soup",
    "farmersdelight:baked_cod_stew": "displaydelight:baked_cod_stew",
    "farmersdelight:noodle_soup": "displaydelight:noodle_soup",
    "farmersdelight:bone_broth": "displaydelight:bone_broth",
    "farmersdelight:bacon_and_eggs": "displaydelight:bacon_and_eggs",
    "farmersdelight:pasta_with_meatballs": "displaydelight:pasta_with_meatballs",
    "farmersdelight:pasta_with_mutton_chop": "displaydelight:pasta_with_mutton_chop",
    "farmersdelight:roasted_mutton_chops": "displaydelight:roasted_mutton_chops",
    "farmersdelight:steak_and_potatoes": "displaydelight:steak_and_potatoes",
    "farmersdelight:vegetable_noodles": "displaydelight:vegetable_noodles",
    "farmersdelight:ratatouille": "displaydelight:ratatouille",
    "farmersdelight:squid_ink_pasta": "displaydelight:squid_ink_pasta",
    "farmersdelight:grilled_salmon": "displaydelight:grilled_salmon",
    "farmersdelight:mushroom_rice": "displaydelight:mushroom_rice",
    "farmersdelight:roast_chicken": "displaydelight:roast_chicken",
    "farmersdelight:stuffed_pumpkin": "displaydelight:stuffed_pumpkin",
    "farmersdelight:honey_glazed_ham": "displaydelight:honey_glazed_ham",
    "farmersdelight:shepherds_pie": "displaydelight:shepherds_pie",
    "farmersdelight:apple_cider": "displaydelight:apple_cider",
    "farmersdelight:melon_juice": "displaydelight:melon_juice",
    "farmersdelight:hot_cocoa": "displaydelight:hot_cocoa",
    "farmersdelight:gleaming_salad": "displaydelight:gleaming_salad",
    "farmersdelight:onion_soup": "displaydelight:onion_soup",

    //Brewin' and Chewin'
    "brewinandchewin:fiery_fondue": "displaydelight:bnc_fiery_fondue",
    "brewinandchewin:scarlet_pierogi": "displaydelight:bnc_scarlet_pierogi",
    "brewinandchewin:horror_lasagna": "displaydelight:bnc_horror_lasagna",
    "brewinandchewin:cheesy_pasta": "displaydelight:bnc_cheesy_pasta",
    "brewinandchewin:creamy_onion_soup": "displaydelight:bnc_creamy_onion_soup",
    "brewinandchewin:vegetable_omelet": "displaydelight:bnc_vegetable_omelet",

    //Corn Delight
    "corn_delight:nachos_bowl": "displaydelight:cd_nachos_bowl",
    "corn_delight:corn_soup": "displaydelight:cd_corn_soup",
    "corn_delight:cornbread_stuffing": "displaydelight:cd_cornbread_stuffing",
    "corn_delight:creamed_corn": "displaydelight:cd_creamed_corn",
    "corn_delight:creamy_corn_drink": "displaydelight:cd_creamy_cor_drink",

    //Pineapple Delight
    "pineapple_delight:pineapple_fried_rice": "displaydelight:pd_pineapple_fried_rice",
    "pineapple_delight:pineapple_ice_cream": "displaydelight:pd_pineapple_ice_cream",
    "pineapple_delight:pineapple_milkshake": "displaydelight:pd_pineapple_milk_shake",
    "pineapple_delight:pineapple_juice": "displaydelight:pd_pineapple_juice",

    //Ocean's Delight
    "oceansdelight:bowl_of_guardian_soup": "displaydelight:od_bowl_of_guardian_soup",
    "oceansdelight:braised_sea_pickle": "displaydelight:od_braised_sea_pickle",
    "oceansdelight:seagrass_salad": "displaydelight:od_seagrass_salad",
    "oceansdelight:squid_rings": "displaydelight:od_squid_rings",

    //Large Meals
    "large_meals:pufferfish_broth": "displaydelight:lm_pufferfish_broth",
    "large_meals:potato_soup": "displaydelight:lm_potato_soup",
    "large_meals:red_soup": "displaydelight:lm_red_soup",
    "large_meals:tomato_egg_soup": "displaydelight:lm_tomato_egg_soup",
    "large_meals:cod_deluxe": "displaydelight:lm_cod_deluxe",
    "large_meals:hearty_lunch": "displaydelight:lm_hearty_lunch",
    "large_meals:chicken_curry": "displaydelight:lm_chicken_curry",
    "large_meals:pasta_with_mushroom_sauce": "displaydelight:lm_pasta_with_mushroom_sauce",
    "large_meals:omurice": "displaydelight:lm_omurice",
    "large_meals:mushroom_pot_pie": "displaydelight:lm_mushroom_pot_pie",
    "large_meals:roasted_mutton_rack": "displaydelight:lm_roasted_mutton_rack",
    "large_meals:sweet_berry_custard": "displaydelight:lm_sweet_berry_custard",
    "large_meals:rice_pudding": "displaydelight:lm_rice_pudding",

    //End's Delight
    "ends_delight:dragon_breath_and_chorus_soup": "displaydelight:edd_dragon_breath_and_chorus_soup",
    "ends_delight:shulker_soup": "displaydelight:edd_shulker_soup",
    "ends_delight:ender_noodle": "displaydelight:edd_ender_noodle",
    "ends_delight:enderman_gristle_stew": "displaydelight:edd_enderman_gristle_stew",
    "ends_delight:stir_fried_shulker_meat": "displaydelight:edd_stir_fried_shulker_meat",
    "ends_delight:roasted_dragon_steak": "displaydelight:edd_roasted_dragon_steak",
    "ends_delight:end_mixed_salad": "displaydelight:edd_end_mixed_salad",
    "ends_delight:assorted_salad": "displaydelight:edd_assorted_salad",
    "ends_delight:ender_congee": "displaydelight:edd_ender_congee",
    "ends_delight:chorus_fruit_milk_tea": "displaydelight:edd_chorus_fruit_milk_tea",
    "ends_delight:chorus_fruit_wine": "displaydelight:edd_chorus_fruit_wine",
    "ends_delight:bubble_tea": "displaydelight:edd_bubble_tea",
    "ends_delight:dragon_breath_soda": "displaydelight:edd_dragon_breath_soda",
    "ends_delight:chorus_flower_tea": "displaydelight:edd_chorus_flower_tea",
    "ends_delight:grilled_shulker": "displaydelight:edd_grilled_shulker",
    "ends_delight:dragon_meat_stew": "displaydelight:edd_dragon_meat_stew",
    "ends_delight:steamed_dragon_egg": "displaydelight:edd_steamed_dragon_egg",
    "ends_delight:dragon_leg_with_sauce": "displaydelight:edd_dragon_leg_with_sauce",

    //Crabber's Delight
    "crabbersdelight:kelp_shake": "displaydelight:crd_kelp_shake",
    "crabbersdelight:coconut_pudding": "displaydelight:crd_coconut_pudding",
    "crabbersdelight:coconut_milk": "displaydelight:crd_coocnut_milk",
    "crabbersdelight:clam_bake": "displaydelight:crd_clam_bake",
    "crabbersdelight:surf_and_turf": "displaydelight:crd_surf_and_turf",
    "crabbersdelight:seafood_gumbo": "displaydelight:crd_seafood_gumbo",
    "crabbersdelight:shrimp_fried_rice": "displaydelight:crd_shrimp_fried_rice",
    "crabbersdelight:coral_crunch": "displaydelight:crd_coral_crunch",
    "crabbersdelight:clam_chowder": "displaydelight:crd_clam_chowder",
    "crabbersdelight:bisque": "displaydelight:crd_bisque",

    //Nether's Delight
    "nethersdelight:plate_of_stuffed_hoglin_snout": "displaydelight:nd_plate_of_stuffed_hoglin_snout",
    "nethersdelight:plate_of_stuffed_hoglin_ham": "displaydelight:nd_plate_of_stuffed_hoglin_ham",
    "nethersdelight:plate_of_stuffed_hoglin_roast": "displaydelight:nd_plate_of_stuffed_hoglin_roast",
    "nethersdelight:strider_moss_stew": "displaydelight:nd_strider_moss_stew",
    "nethersdelight:warped_moldy_meat": "displaydelight:nd_warped_moldy_meat",
    "nethersdelight:grilled_strider": "displaydelight:nd_grilled_strider"
};